server:
  port: 3000
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: wook
    password: wook1234
  jpa:
    open-in-view: true #razy loading이 가능 , 영속성 컨텍스트 시작을 서블릿이 시작되는 시점부터 할것을 지정
    hibernate:
      ddl-auto: update  #create이면 서버 실행을 할때마나 테이블 삭제후 새로 생성됨 주의 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #Entity를 만들때 필드 변수명 그대로 테이블 컬럼으로 지정함
      use-new-id-generator-mappings: false #jpa의 기본 전략을 따르지않음
    show-sql: true  #console창에 표시
    properties: 
      hibernate.format_sql: true #console창에 정렬되어 표시
